jdk:
    - oraclejdk8
install:
    - mvn io.takari:maven:wrapper
    - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
    - ./mvnw test
after_success:
    - bash <(curl -s https://codecov.io/bash)